# Configuration for dev development using MySQL database

spring:
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca/CSCI5308_4_DEVINT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEVINT_DB_USER}
    password: ${DEVINT_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: mysql
      mode: always

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG

server:
  port: 8081
